package de.kuschku.steamaudio.lib.context;

import com.sun.jna.Callback;
import com.sun.jna.Pointer;

public interface IPLLogFunction extends Callback {
    /**
     * Prototype of a callback that logs a message generated by Phonon. This may be implemented in any suitable way,
     * such as appending to a log file, displaying a dialog box, etc. The default behavior is to print to {@code
     * stdout}.
     *
     * @param message The message to log.
     */
    void apply(Pointer message);
}
