package de.kuschku.steamaudio.lib.context;

import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.Ptr;

public abstract class IPLLogFunction extends Callback<IPLLogFunction> {
    /**
     * Prototype of a callback that logs a message generated by Phonon. This may be implemented in any suitable way,
     * such as appending to a log file, displaying a dialog box, etc. The default behavior is to print to {@code
     * stdout}.
     *
     * @param message The message to log.
     */
    public void apply(Pointer<Byte> message) {
        apply(Pointer.getPeer(message));
    }

    /**
     * Prototype of a callback that logs a message generated by Phonon. This may be implemented in any suitable way,
     * such as appending to a log file, displaying a dialog box, etc. The default behavior is to print to {@code
     * stdout}.
     *
     * @param message The message to log.
     */
    @SuppressWarnings("deprecation")
    public void apply(@Ptr long message) {
        apply(Pointer.pointerToAddress(message, Byte.class));
    }
}
