/**
 * <h1>Ambisonics Panning Effect</h1>
 * <p>
 * Functionality for renderign Ambisonics data by panning it to standard speaker layouts. Ambisonics is a powerful
 * format for encoding 3D sound fields, and exchanging them. Phonon can encode data into Ambisonics using the Panning
 * Effect: to spatialize a sound source and create an Ambisonics track, use the Panning Effect with {@link
 * de.kuschku.steamaudio.lib.audiobuffer.IPLAudioFormat#channelLayoutType} set to {@link
 * de.kuschku.steamaudio.lib.audiobuffer.IPLChannelLayoutType#IPL_CHANNELLAYOUTTYPE_AMBISONICS}.
 * <p>
 * Phonon can also decode and render Ambisonics data, using panning. This involves approximating the sound field as if
 * it were generated by sound coming from each speaker.
 * <p>
 * Ambisonics also allows 3D audio rendering in VR to be significantly accelerated: instead of applying object-based
 * binaural rendering to each source individually, the sources can be encoded into Ambisonics first, then mixed, and
 * finally the mix can be rendered using Ambisonics binaural rendering. This saves CPU cycles, at the cost of some
 * spatialization accuracy.
 */
package de.kuschku.steamaudio.lib.ambisonicspanning;